version: '3.8'  #version of docker

services:
  api:
    build: .
    container_name: fraud_detection_system
    ports:
      - "8000:8000"
    depends_on:
      kafka:
       condition: service_healthy  #wait for the kafka to be ready
    environment:
      KAFKA_TRANSACTION_TOPIC: transactions  #the topic where the datas from the frontend is passed into kafka
      KAFKA_FRAUD_RESULT_TOPIC: fraud_results   #the topic where the result of whether the passed transaction data is fraud or not is stored
      KAFKA_DLQ_TOPIC: transactions_dlq  #the topic where error and message saying why the detection system crashed is stored allowing us to debug problematic transactions later without stopping the rest of the pipeline.
      KAFKA_CONFIG_PATH: /app/secrets/client.properties  #configuration file for kafka client , kafka confluent is used 
    volumes:
      # Mounting local client.properties into the container as read-only at the time of runtime as our kafka configuration file contains sensitive information such as credentials and we want to keep it secure.
      # This keeps credentials OFF the image layer (never baked into Docker image) only available at the docker container runtime
      - ./client.properties:/app/secrets/client.properties:ro  
    # Adding a health check to ensure the application is running and healthy. This allows Docker to automatically restart the container if it becomes unhealthy, improving the reliability of our fraud detection system.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s 
  dashboard:
    build: .
    container_name: fraud_detection_dashboard
    ports:
      - "8501:8501"
    depends_on:
      kafka:
       condition: service_healthy  #wait for the kafka to be ready
    environment:
      KAFKA_TRANSACTION_TOPIC: transactions  #the topic where the datas from the frontend is passed into kafka
      KAFKA_FRAUD_RESULT_TOPIC: fraud_results   #the topic where the result of whether the passed transaction data is fraud or not is stored
      KAFKA_DLQ_TOPIC: transactions_dlq  #the topic where error and message saying why the detection system crashed is stored allowing us to debug problematic transactions later without stopping the rest of the pipeline.
      KAFKA_CONSUMER_GROUP_ID: fraud_detection_group

      KAFKA_CONFIG_PATH: /app/secrets/client.properties  #configuration file for kafka client , kafka confluent is used 
    volumes:
      # Mounting local client.properties into the container as read-only at the time of runtime as our kafka configuration file contains sensitive information such as credentials and we want to keep it secure.
      # This keeps credentials OFF the image layer (never baked into Docker image) only available at the docker container runtime
      - ./client.properties:/app/secrets/client.properties:ro  
    # Adding a health check to ensure the application is running and healthy. This allows Docker to automatically restart the container if it becomes unhealthy, improving the reliability of our fraud detection system.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s      



