FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get install -y curl
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
CMD ["sh", "-c", "streamlit run ui.py --server.address=0.0.0.0 --server.port=$PORT --server.headless=true --server.fileWatcherType=none"]